-- seed.sql — demo data. Generated by scripts/seed.js. Run by hand,
-- ONCE, on a fresh database. Never against a live tenant.
-- All demo passwords: Passw0rd!

DELETE FROM users WHERE email = 'super@demo.hms';
INSERT INTO users (tenant_id, name, email, password_hash, role)
VALUES (NULL, 'Kaizen Platform Admin', 'super@kaizen.platform', '$2b$12$0nff8IKrQVj704qlbik9aunDOe6s75h5PVP9o6OI2gCPuF5CBe7qm', 'SUPER_ADMIN')
ON DUPLICATE KEY UPDATE name = VALUES(name), password_hash = VALUES(password_hash), role = 'SUPER_ADMIN';

-- Demo Hospital (HOSPITAL)
INSERT INTO tenants (name, slug, type, active) VALUES ('Demo Hospital', 'demo', 'HOSPITAL', 1)
ON DUPLICATE KEY UPDATE name = VALUES(name), type = VALUES(type), active = 1;
SET @tid = (SELECT id FROM tenants WHERE slug = 'demo');
INSERT INTO tenant_modules (tenant_id, module_name, is_active) VALUES (@tid, 'PHARMACY', 1)
ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO tenant_modules (tenant_id, module_name, is_active) VALUES (@tid, 'DOCTOR_OPD', 1)
ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO tenant_modules (tenant_id, module_name, is_active) VALUES (@tid, 'LAB', 1)
ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO tenant_modules (tenant_id, module_name, is_active) VALUES (@tid, 'BILLING', 1)
ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO tenant_modules (tenant_id, module_name, is_active) VALUES (@tid, 'IPD', 1)
ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO users (tenant_id, name, email, password_hash, role)
VALUES (@tid, 'Demo Admin', 'admin@demo.hms', '$2b$12$0nff8IKrQVj704qlbik9aunDOe6s75h5PVP9o6OI2gCPuF5CBe7qm', 'HOSPITAL_ADMIN')
ON DUPLICATE KEY UPDATE name = VALUES(name), role = VALUES(role), password_hash = VALUES(password_hash);
INSERT INTO users (tenant_id, name, email, password_hash, role)
VALUES (@tid, 'Demo Reception', 'reception@demo.hms', '$2b$12$0nff8IKrQVj704qlbik9aunDOe6s75h5PVP9o6OI2gCPuF5CBe7qm', 'RECEPTIONIST')
ON DUPLICATE KEY UPDATE name = VALUES(name), role = VALUES(role), password_hash = VALUES(password_hash);
INSERT INTO users (tenant_id, name, email, password_hash, role)
VALUES (@tid, 'Dr. Demo', 'doctor@demo.hms', '$2b$12$0nff8IKrQVj704qlbik9aunDOe6s75h5PVP9o6OI2gCPuF5CBe7qm', 'DOCTOR')
ON DUPLICATE KEY UPDATE name = VALUES(name), role = VALUES(role), password_hash = VALUES(password_hash);
INSERT INTO users (tenant_id, name, email, password_hash, role)
VALUES (@tid, 'Nurse Demo', 'nurse@demo.hms', '$2b$12$0nff8IKrQVj704qlbik9aunDOe6s75h5PVP9o6OI2gCPuF5CBe7qm', 'NURSE')
ON DUPLICATE KEY UPDATE name = VALUES(name), role = VALUES(role), password_hash = VALUES(password_hash);
INSERT INTO users (tenant_id, name, email, password_hash, role)
VALUES (@tid, 'Demo Pharmacist', 'pharmacist@demo.hms', '$2b$12$0nff8IKrQVj704qlbik9aunDOe6s75h5PVP9o6OI2gCPuF5CBe7qm', 'PHARMACIST')
ON DUPLICATE KEY UPDATE name = VALUES(name), role = VALUES(role), password_hash = VALUES(password_hash);
INSERT INTO users (tenant_id, name, email, password_hash, role)
VALUES (@tid, 'Demo Lab Tech', 'lab@demo.hms', '$2b$12$0nff8IKrQVj704qlbik9aunDOe6s75h5PVP9o6OI2gCPuF5CBe7qm', 'LAB_TECH')
ON DUPLICATE KEY UPDATE name = VALUES(name), role = VALUES(role), password_hash = VALUES(password_hash);
INSERT INTO users (tenant_id, name, email, password_hash, role)
VALUES (@tid, 'Demo Billing', 'billing@demo.hms', '$2b$12$0nff8IKrQVj704qlbik9aunDOe6s75h5PVP9o6OI2gCPuF5CBe7qm', 'BILLING_STAFF')
ON DUPLICATE KEY UPDATE name = VALUES(name), role = VALUES(role), password_hash = VALUES(password_hash);
INSERT INTO form_templates (tenant_id, form_type, fields)
VALUES (@tid, 'PATIENT_REGISTRATION', '[{"fieldName":"address","label":"Address","type":"textarea","required":false,"order":0},{"fieldName":"blood_group","label":"Blood group","type":"select","required":false,"order":1,"options":["A+","A-","B+","B-","O+","O-","AB+","AB-"]}]')
ON DUPLICATE KEY UPDATE fields = VALUES(fields);
INSERT INTO beds (tenant_id, ward_type, bed_number, status)
VALUES (@tid, 'GENERAL', 'G-101', 'VACANT')
ON DUPLICATE KEY UPDATE ward_type = VALUES(ward_type);
INSERT INTO beds (tenant_id, ward_type, bed_number, status)
VALUES (@tid, 'GENERAL', 'G-102', 'VACANT')
ON DUPLICATE KEY UPDATE ward_type = VALUES(ward_type);
INSERT INTO beds (tenant_id, ward_type, bed_number, status)
VALUES (@tid, 'GENERAL', 'G-103', 'VACANT')
ON DUPLICATE KEY UPDATE ward_type = VALUES(ward_type);
INSERT INTO beds (tenant_id, ward_type, bed_number, status)
VALUES (@tid, 'PRIVATE', 'P-201', 'VACANT')
ON DUPLICATE KEY UPDATE ward_type = VALUES(ward_type);
INSERT INTO beds (tenant_id, ward_type, bed_number, status)
VALUES (@tid, 'PRIVATE', 'P-202', 'VACANT')
ON DUPLICATE KEY UPDATE ward_type = VALUES(ward_type);
INSERT INTO beds (tenant_id, ward_type, bed_number, status)
VALUES (@tid, 'ICU', 'ICU-1', 'VACANT')
ON DUPLICATE KEY UPDATE ward_type = VALUES(ward_type);
INSERT INTO beds (tenant_id, ward_type, bed_number, status)
VALUES (@tid, 'ICU', 'ICU-2', 'VACANT')
ON DUPLICATE KEY UPDATE ward_type = VALUES(ward_type);

-- Dr. Mehra's Clinic (DOCTOR_SOLO)
INSERT INTO tenants (name, slug, type, active) VALUES ('Dr. Mehra''s Clinic', 'drmehra', 'DOCTOR_SOLO', 1)
ON DUPLICATE KEY UPDATE name = VALUES(name), type = VALUES(type), active = 1;
SET @tid = (SELECT id FROM tenants WHERE slug = 'drmehra');
INSERT INTO tenant_modules (tenant_id, module_name, is_active) VALUES (@tid, 'DOCTOR_OPD', 1)
ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO users (tenant_id, name, email, password_hash, role)
VALUES (@tid, 'Dr. Anil Mehra', 'owner@drmehra.clinic', '$2b$12$0nff8IKrQVj704qlbik9aunDOe6s75h5PVP9o6OI2gCPuF5CBe7qm', 'OWNER_DOCTOR')
ON DUPLICATE KEY UPDATE name = VALUES(name), role = VALUES(role), password_hash = VALUES(password_hash);

-- City Chemist (PHARMACY_SOLO)
INSERT INTO tenants (name, slug, type, active) VALUES ('City Chemist', 'citychemist', 'PHARMACY_SOLO', 1)
ON DUPLICATE KEY UPDATE name = VALUES(name), type = VALUES(type), active = 1;
SET @tid = (SELECT id FROM tenants WHERE slug = 'citychemist');
INSERT INTO tenant_modules (tenant_id, module_name, is_active) VALUES (@tid, 'PHARMACY', 1)
ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO users (tenant_id, name, email, password_hash, role)
VALUES (@tid, 'Suresh (City Chemist)', 'owner@citychemist.shop', '$2b$12$0nff8IKrQVj704qlbik9aunDOe6s75h5PVP9o6OI2gCPuF5CBe7qm', 'OWNER_PHARMACIST')
ON DUPLICATE KEY UPDATE name = VALUES(name), role = VALUES(role), password_hash = VALUES(password_hash);

-- Prabhat Diagnostic Lab (LAB_SOLO)
INSERT INTO tenants (name, slug, type, active) VALUES ('Prabhat Diagnostic Lab', 'prabhatlab', 'LAB_SOLO', 1)
ON DUPLICATE KEY UPDATE name = VALUES(name), type = VALUES(type), active = 1;
SET @tid = (SELECT id FROM tenants WHERE slug = 'prabhatlab');
INSERT INTO tenant_modules (tenant_id, module_name, is_active) VALUES (@tid, 'LAB', 1)
ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO users (tenant_id, name, email, password_hash, role)
VALUES (@tid, 'Prabhat Lab Owner', 'owner@prabhatlab.co', '$2b$12$0nff8IKrQVj704qlbik9aunDOe6s75h5PVP9o6OI2gCPuF5CBe7qm', 'OWNER_LAB_TECH')
ON DUPLICATE KEY UPDATE name = VALUES(name), role = VALUES(role), password_hash = VALUES(password_hash);

