/**
 * Generates migrations/seed.sql — demo tenants of every type + a platform
 * SUPER_ADMIN. It does NOT connect to any database. The project owner runs
 * the generated file by hand, once, on a fresh database (never against a
 * live tenant). See CLAUDE.md "Database rule".
 *
 * Usage: npm run db:seed   (writes the file, prints nothing else)
 *
 * Demo logins (all password: Passw0rd!):
 *   super@kaizen.platform    SUPER_ADMIN      (no tenant)
 *   admin@demo.hms           HOSPITAL_ADMIN   } tenant "demo" (HOSPITAL,
 *   reception@demo.hms       RECEPTIONIST     }  all 4 modules)
 *   doctor@demo.hms          DOCTOR           }
 *   nurse@demo.hms           NURSE            }
 *   pharmacist@demo.hms      PHARMACIST       }
 *   lab@demo.hms             LAB_TECH         }
 *   billing@demo.hms         BILLING_STAFF    }
 *   owner@drmehra.clinic     OWNER_DOCTOR     tenant "drmehra" (DOCTOR_SOLO)
 *   owner@citychemist.shop   OWNER_PHARMACIST tenant "citychemist" (PHARMACY_SOLO)
 *   owner@prabhatlab.co      OWNER_LAB_TECH   tenant "prabhatlab" (LAB_SOLO)
 */
"use strict";

const fs = require("fs");
const path = require("path");
const bcrypt = require("bcryptjs");

const PASSWORD = "Passw0rd!";
const OUT = path.resolve(__dirname, "..", "migrations", "seed.sql");

const SUPER_ADMIN = { name: "Kaizen Platform Admin", email: "super@kaizen.platform" };

const TENANTS = [
  {
    name: "Demo Hospital",
    slug: "demo",
    type: "HOSPITAL",
    modules: ["PHARMACY", "DOCTOR_OPD", "LAB", "BILLING", "IPD"],
    beds: [
      ["GENERAL", "G-101"], ["GENERAL", "G-102"], ["GENERAL", "G-103"],
      ["PRIVATE", "P-201"], ["PRIVATE", "P-202"],
      ["ICU", "ICU-1"], ["ICU", "ICU-2"],
    ],
    users: [
      ["Demo Admin", "admin@demo.hms", "HOSPITAL_ADMIN"],
      ["Demo Reception", "reception@demo.hms", "RECEPTIONIST"],
      ["Dr. Demo", "doctor@demo.hms", "DOCTOR"],
      ["Nurse Demo", "nurse@demo.hms", "NURSE"],
      ["Demo Pharmacist", "pharmacist@demo.hms", "PHARMACIST"],
      ["Demo Lab Tech", "lab@demo.hms", "LAB_TECH"],
      ["Demo Billing", "billing@demo.hms", "BILLING_STAFF"],
    ],
    regFields: [
      { fieldName: "address", label: "Address", type: "textarea", required: false, order: 0 },
      {
        fieldName: "blood_group",
        label: "Blood group",
        type: "select",
        required: false,
        order: 1,
        options: ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"],
      },
    ],
  },
  {
    name: "Dr. Mehra's Clinic",
    slug: "drmehra",
    type: "DOCTOR_SOLO",
    modules: ["DOCTOR_OPD"],
    users: [["Dr. Anil Mehra", "owner@drmehra.clinic", "OWNER_DOCTOR"]],
  },
  {
    name: "City Chemist",
    slug: "citychemist",
    type: "PHARMACY_SOLO",
    modules: ["PHARMACY"],
    users: [["Suresh (City Chemist)", "owner@citychemist.shop", "OWNER_PHARMACIST"]],
  },
  {
    name: "Prabhat Diagnostic Lab",
    slug: "prabhatlab",
    type: "LAB_SOLO",
    modules: ["LAB"],
    users: [["Prabhat Lab Owner", "owner@prabhatlab.co", "OWNER_LAB_TECH"]],
  },
];

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";

async function main() {
  const hash = await bcrypt.hash(PASSWORD, 12);
  const L = [];

  L.push("-- seed.sql — demo data. Generated by scripts/seed.js. Run by hand,");
  L.push("-- ONCE, on a fresh database. Never against a live tenant.");
  L.push("-- All demo passwords: " + PASSWORD);
  L.push("");
  L.push("DELETE FROM users WHERE email = 'super@demo.hms';");
  L.push(
    `INSERT INTO users (tenant_id, name, email, password_hash, role)\n` +
      `VALUES (NULL, ${q(SUPER_ADMIN.name)}, ${q(SUPER_ADMIN.email)}, ${q(hash)}, 'SUPER_ADMIN')\n` +
      `ON DUPLICATE KEY UPDATE name = VALUES(name), password_hash = VALUES(password_hash), role = 'SUPER_ADMIN';`,
  );
  L.push("");

  for (const t of TENANTS) {
    L.push(`-- ${t.name} (${t.type})`);
    L.push(
      `INSERT INTO tenants (name, slug, type, active) VALUES (${q(t.name)}, ${q(t.slug)}, ${q(t.type)}, 1)\n` +
        `ON DUPLICATE KEY UPDATE name = VALUES(name), type = VALUES(type), active = 1;`,
    );
    L.push(`SET @tid = (SELECT id FROM tenants WHERE slug = ${q(t.slug)});`);
    for (const m of t.modules) {
      L.push(
        `INSERT INTO tenant_modules (tenant_id, module_name, is_active) VALUES (@tid, ${q(m)}, 1)\n` +
          `ON DUPLICATE KEY UPDATE is_active = 1;`,
      );
    }
    for (const [name, email, role] of t.users) {
      L.push(
        `INSERT INTO users (tenant_id, name, email, password_hash, role)\n` +
          `VALUES (@tid, ${q(name)}, ${q(email)}, ${q(hash)}, ${q(role)})\n` +
          `ON DUPLICATE KEY UPDATE name = VALUES(name), role = VALUES(role), password_hash = VALUES(password_hash);`,
      );
    }
    if (t.regFields) {
      L.push(
        `INSERT INTO form_templates (tenant_id, form_type, fields)\n` +
          `VALUES (@tid, 'PATIENT_REGISTRATION', ${q(JSON.stringify(t.regFields))})\n` +
          `ON DUPLICATE KEY UPDATE fields = VALUES(fields);`,
      );
    }
    if (t.beds) {
      for (const [wardType, bedNumber] of t.beds) {
        L.push(
          `INSERT INTO beds (tenant_id, ward_type, bed_number, status)\n` +
            `VALUES (@tid, ${q(wardType)}, ${q(bedNumber)}, 'VACANT')\n` +
            `ON DUPLICATE KEY UPDATE ward_type = VALUES(ward_type);`,
        );
      }
    }
    L.push("");
  }

  fs.writeFileSync(OUT, L.join("\n") + "\n");
  console.log(`Wrote ${path.relative(process.cwd(), OUT)} — apply it by hand.`);
}

main().catch((e) => {
  console.error(e.message || e);
  process.exit(1);
});
